# This is a basic workflow to help you get started with Actions

name: Workflow test

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm install sanity sanity/client fs
      - name: Run script
        run: node .github/workflows/upload/migrate_data.js
        env:
          SANITY_PROJECT_TOKEN: ${{ secrets.SANITY_PROJECT_TOKEN }}
